import 'dart:typed_data';
import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'agreement_model.dart';
import 'agreement_repository.dart';
import '../../../core/services/delivery_service.dart';

class PdfService {
  PdfService(this._repo, this._delivery, this._storage, this._firestore);

  final AgreementRepository _repo;
  final DeliveryService _delivery;
  final FirebaseStorage _storage;
  final FirebaseFirestore _firestore;

  static final _dateFmt = DateFormat('MMMM d, yyyy');

  /// Generates a PDF, saves it locally, uploads to Storage, marks signed,
  /// then triggers delivery. Returns the local file path on success.
  Future<String?> generate({
    required AgreementModel agreement,
    required Uint8List agentSignatureBytes,
    required Uint8List buyerSignatureBytes,
  }) async {
    final pdf = pw.Document();

    final agentSigImage = pw.MemoryImage(agentSignatureBytes);
    final buyerSigImage = pw.MemoryImage(buyerSignatureBytes);
    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(48),
        build: (ctx) => [
          _header(agreement),
          pw.SizedBox(height: 20),
          _sectionTitle('Parties'),
          _labelValue('Buyer', agreement.buyerName),
          _labelValue('Buyer email', agreement.buyerEmail),
          _labelValue('Agent', agreement.agentName),
          _labelValue('Agent email', agreement.agentEmail),
          _labelValue('Brokerage', agreement.brokerageName),
          pw.SizedBox(height: 16),
          _sectionTitle('Agreement Terms'),
          _labelValue('Property scope', agreement.propertyScope),
          _labelValue('Buyer agent compensation', agreement.compensation),
          _labelValue('Start date', _dateFmt.format(agreement.startDate)),
          _labelValue('End date', _dateFmt.format(agreement.endDate)),
          pw.SizedBox(height: 16),
          _sectionTitle('NAR Compliance'),
          pw.Text(
            'This agreement is entered into pursuant to the NAR settlement requirements '
            'effective August 17, 2024. The buyer agrees to the stated compensation '
            'arrangement before touring any properties.',
            style: const pw.TextStyle(fontSize: 10),
          ),
          pw.SizedBox(height: 24),
          _sectionTitle('Signatures'),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: _signatureBlock(
                  label: 'Agent signature',
                  name: agreement.agentName,
                  imageProvider: agentSigImage,
                  date: now,
                ),
              ),
              pw.SizedBox(width: 24),
              pw.Expanded(
                child: _signatureBlock(
                  label: 'Buyer signature',
                  name: agreement.buyerName,
                  imageProvider: buyerSigImage,
                  date: now,
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by Threshold on ${_dateFmt.format(now)}',
            style: pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
            ),
          ),
        ],
      ),
    );

    final bytes = await pdf.save();

    // Save to local device storage.
    final dir = await getApplicationDocumentsDirectory();
    final safeName = agreement.buyerName.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
    final filename = 'agreement_${safeName}_${agreement.id.substring(0, 8)}.pdf';
    final file = File('${dir.path}/$filename');
    await file.writeAsBytes(bytes);
    final localPath = file.path;

    // Upload to Firebase Storage.
    String? storagePath;
    try {
      final ref = _storage
          .ref()
          .child('agreements/${agreement.agentId}/$filename');
      await ref.putData(bytes, SettableMetadata(contentType: 'application/pdf'));
      storagePath = ref.fullPath;
    } catch (_) {
      // Upload failure is non-fatal; we still have the local copy.
    }

    // Mark as signed in Firestore.
    final signed = agreement.copyWith(
      status: AgreementStatus.pendingDelivery,
      localPdfPath: localPath,
      storagePdfPath: storagePath,
      signedAt: now,
    );

    await _repo.update(agreement.id, {
      'status': 'pending_delivery',
      'localPdfPath': localPath,
      if (storagePath != null) 'storagePdfPath': storagePath,
      'signedAt': Timestamp.fromDate(now),
    });

    // Attempt delivery; if it fails the connectivity watcher will retry.
    await _delivery.deliver(signed);

    return localPath;
  }

  pw.Widget _header(AgreementModel a) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Buyer Representation Agreement',
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.Text(
            a.formState,
            style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),
          pw.Divider(),
        ],
      );

  pw.Widget _sectionTitle(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: pw.Text(
          text,
          style: pw.TextStyle(
            fontSize: 12,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.green900,
          ),
        ),
      );

  pw.Widget _labelValue(String label, String value) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4),
        child: pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.SizedBox(
              width: 140,
              child: pw.Text(
                '$label:',
                style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.Expanded(
              child: pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
            ),
          ],
        ),
      );

  pw.Widget _signatureBlock({
    required String label,
    required String name,
    required pw.ImageProvider imageProvider,
    required DateTime date,
  }) =>
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label,
              style: pw.TextStyle(
                  fontSize: 10, fontWeight: pw.FontWeight.bold)),
          pw.Container(
            height: 60,
            margin: const pw.EdgeInsets.symmetric(vertical: 4),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400),
            ),
            child: pw.Image(imageProvider, fit: pw.BoxFit.contain),
          ),
          pw.Text(name, style: const pw.TextStyle(fontSize: 10)),
          pw.Text(
            DateFormat('MM/dd/yyyy HH:mm').format(date),
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      );
}

final pdfServiceProvider = Provider<PdfService>((ref) => PdfService(
      ref.read(agreementRepositoryProvider),
      ref.read(deliveryServiceProvider),
      FirebaseStorage.instance,
      FirebaseFirestore.instance,
    ));
